local bpTo = "Backpack"
Self.WithdrawItems(0, {"boots of haste", bpTo, 100})
Self.WithdrawItems(0, {"Amber Staff", bpTo, 100})
Self.WithdrawItems(0, {"Assassin Dagger", bpTo, 100})
Self.WithdrawItems(0, {"Demon Shield", bpTo, 100})
Self.WithdrawItems(0, {"Demonrage Sword", bpTo, 100})
Self.WithdrawItems(0, {"Dragon Scale Mail", bpTo, 100})
Self.WithdrawItems(0, {"Dragon Slayer", bpTo, 100})
Self.WithdrawItems(0, {"Dragonbone Staff", bpTo, 100})
Self.WithdrawItems(0, {"Dreaded Cleaver", bpTo, 100})
Self.WithdrawItems(0, {"War Axe", bpTo, 100})
Self.WithdrawItems(0, {"Vile Axe", bpTo, 100})
Self.WithdrawItems(0, {"Terra Mantle", bpTo, 100})
Self.WithdrawItems(0, {"Terra Legs", bpTo, 100})
Self.WithdrawItems(0, {"Terra Hood", bpTo, 100})
Self.WithdrawItems(0, {"Terra Boots", bpTo, 100})
Self.WithdrawItems(0, {"Steel Boots", bpTo, 100})
Self.WithdrawItems(0, {"Spiked Squelcher", bpTo, 100})
Self.WithdrawItems(0, {"Skull Helmet", bpTo, 100})
Self.WithdrawItems(0, {"Skullcracker Armor", bpTo, 100})
Self.WithdrawItems(0, {"Ruthless Axe", bpTo, 100})
Self.WithdrawItems(0, {"Platinum Amulet", bpTo, 100})
Self.WithdrawItems(0, {"Naginata", bpTo, 100})
Self.WithdrawItems(0, {"Mastermind Shield", bpTo, 100})
Self.WithdrawItems(0, {"Magma Monocle", bpTo, 100})
Self.WithdrawItems(0, {"Magma Boots", bpTo, 100})
Self.WithdrawItems(0, {"Magic Plate Armor", bpTo, 100})
Self.WithdrawItems(0, {"Jade Hammer", bpTo, 100})
Self.WithdrawItems(0, {"Golden Legs", bpTo, 100})
Self.WithdrawItems(0, {"Gold Ring", bpTo, 100})
Self.WithdrawItems(0, {"", bpTo, 100})