--[[
	This is a XenoBot example script, intended to
	teach new users about the scripting API and 
	act as script that is usable in actual play.
	
	ringReload.lua - reloading rings

	** DO NOT EDIT THIS FILE. INSTEAD, COPY IT TO
	"Documents\XenoBot\Scripts" AND EDIT THE COPY. **
]]--


--set the name or ID of the ring here
local ring = "dwarven ring"

-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------

--this decides whether we have an id or a name, converting names into ids
local ringID = Item.GetItemIDFromDualInput(ring)

--this continuously loops, executing the code inside over and over again
while (true) do
	--this checks to see if we have the wrong ring on
    if (Self.Ring().id ~= Item.GetRingActiveID(ringID)) then
		--if we do have the wrong ring on, this equips it
        Self.Equip(ringID, "ring")
    end
    
    --this causes the loop to wait between 1.5 and 2.5 seconds before retrying
    wait(1500, 2500)
end