Module.New('Spam', function(spam)

	Self.Say("SELL XENOBOT FULL AFK SCRIPTS BY MATHIA ALL SCRIPTS HAVE SOFT REFILLER ITEM SELLER TASKER ETC SCIPTS LIST HERE . http://wklej.org/id/3225661/ I SPEAK POLISH AND ENGLISH")

	spam:Delay(7000)

end)